#!/usr/bin/env bash
# Phase 3: cross-references the real (rust-analyzer-verified) module
# dependency graph from `cargo modules` against graphify's community
# detection in docs/graph/graph.json, to catch directory/coupling
# mismatches - a directory that fragments across many communities, or a
# graphify community that quietly spans many top-level directories.
#
# Advisory only - writes docs/architecture/module-coupling.md and
# docs/architecture/dependency.dot (open the .dot with any Graphviz viewer,
# or `dot -Tsvg dependency.dot -o dependency.svg` if you have graphviz).
#
# Usage: scripts/analyze-module-coupling.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"
mkdir -p docs/architecture

if ! command -v cargo-modules >/dev/null 2>&1; then
  echo "[analyze] cargo-modules not found - install with: cargo install cargo-modules" >&2
  exit 1
fi

if [ ! -f docs/graph/graph.json ]; then
  echo "[analyze] docs/graph/graph.json not found - run scripts/update-knowledge-graph.sh first" >&2
  exit 1
fi

GRAPHIFY_PYTHON="$(cat docs/graph/.graphify_python 2>/dev/null || command -v python3)"

cargo modules dependencies --lib --no-fns --no-types --no-traits --no-owns \
  --no-externs --no-sysroot > docs/architecture/dependency.dot 2>/dev/null

if command -v dot >/dev/null 2>&1; then
  dot -Tsvg docs/architecture/dependency.dot -o docs/architecture/dependency.svg
  echo "[analyze] rendered docs/architecture/dependency.svg (graphviz found)"
else
  echo "[analyze] graphviz 'dot' not installed - kept dependency.dot only (render it yourself: dot -Tsvg dependency.dot -o dependency.svg)"
fi

"$GRAPHIFY_PYTHON" <<'PYEOF'
import json
import re
from collections import Counter, defaultdict
from pathlib import Path

dot_text = Path("docs/architecture/dependency.dot").read_text(encoding="utf-8")

# "crustly::llm::agent::service" -> "llm" (first path segment); the crate
# root itself ("crustly") maps to "(root)".
def top_level_group(module_path: str) -> str:
    body = module_path.removeprefix("crustly::")
    if body == "crustly" or body == "":
        return "(root)"
    return body.split("::")[0]

edge_re = re.compile(r'"(crustly(?:::[\w:]+)?)"\s*->\s*"(crustly(?:::[\w:]+)?)"\s*\[label="uses"')
group_edges: set[tuple[str, str]] = set()
fine_edges: list[tuple[str, str, str, str]] = []  # (g_src, g_dst, src, dst)
for src, dst in edge_re.findall(dot_text):
    g_src, g_dst = top_level_group(src), top_level_group(dst)
    if g_src != g_dst:
        group_edges.add((g_src, g_dst))
        fine_edges.append((g_src, g_dst, src, dst))

# docs/architecture/containers.md declares a one-directional layering:
# UI (tui/cli) -> Application/Provider (llm) -> Service (services) -> DB (db).
# An edge from db/llm/services INTO tui is that layering running backwards.
BELOW_UI = {"db", "llm", "services", "config"}
layering_violations = [
    (s, d) for (gs, gd, s, d) in fine_edges if gd == "tui" and gs in BELOW_UI
]

lines = []
lines.append("# Module Coupling: cargo-modules vs graphify communities")
lines.append("")
lines.append("Generated by `scripts/analyze-module-coupling.sh`. Advisory only.")
lines.append("")
lines.append("## Cross-directory module dependencies (rust-analyzer-verified)")
lines.append("")
lines.append("`cargo modules dependencies` uses rust-analyzer's semantic model, "
              "so these edges are ground truth (unlike graphify's tree-sitter "
              "text extraction, which the Phase 2 report found misses some "
              "import styles). Grouped by top-level `src/` module; self-edges "
              "within a group are omitted.")
lines.append("")
by_src: dict[str, list[str]] = defaultdict(list)
for s, d in sorted(group_edges):
    by_src[s].append(d)
for s in sorted(by_src):
    lines.append(f"- **{s}** -> {', '.join(sorted(by_src[s]))}")
lines.append("")

lines.append("## Layering check against docs/architecture/containers.md")
lines.append("")
lines.append("`containers.md` declares a one-directional layering: UI "
              "(`tui`/`cli`) depends on Application/Provider (`llm`), which "
              "depends on Service (`services`), which depends on Database "
              "(`db`). An edge running the other way - `db`, `llm`, "
              "`services`, or `config` depending on `tui` - is that layering "
              "inverted.")
lines.append("")
if not layering_violations:
    lines.append("None found - no lower-layer module depends on `tui`.")
else:
    lines.append(f"**{len(layering_violations)} found**, all converging on the same target:")
    lines.append("")
    for s, d in sorted(set(layering_violations)):
        lines.append(f"- `{s}` -> `{d}`")
    lines.append("")
    targets = sorted({d for _, d in layering_violations})
    lines.append(f"Root cause: `{', '.join(targets)}` defines domain types "
                 "(e.g. the Plan data model) that the database, tool, and "
                 "service layers need, but they physically live in `tui/`. "
                 "Every consumer below the UI layer ends up depending on the "
                 "UI module to get at its own domain types. This also lines "
                 "up with `docs/graph/GRAPH_REPORT.md`'s god-node list, "
                 "where `PlanDocument` is a top connector. Fix: move the "
                 "shared domain types out of `tui/` into their own module "
                 "(e.g. a `domain` or `plan` module at the crate root) that "
                 "`tui`, `db`, `llm`, and `services` all depend on instead of "
                 "depending on each other.")
lines.append("")

# --- Cross-reference against graphify communities ---------------------------
graph = json.loads(Path("docs/graph/graph.json").read_text(encoding="utf-8"))


def file_group(source_file: str) -> str | None:
    if not source_file or not source_file.startswith("src/"):
        return None
    rest = source_file[len("src/"):]
    if "/" in rest:
        return rest.split("/", 1)[0]
    return rest.removesuffix(".rs")  # top-level file, e.g. src/error.rs -> "error"


group_communities: dict[str, Counter] = defaultdict(Counter)
for n in graph["nodes"]:
    g = file_group(n.get("source_file", ""))
    if g is None:
        continue
    comm = n.get("community")
    if comm is not None:
        group_communities[g][comm] += 1

lines.append("## Directory cohesion (graphify community spread)")
lines.append("")
lines.append("For each top-level `src/` module, how many distinct graphify "
              "communities its symbols fall into. A module split across many "
              "communities either genuinely groups unrelated concerns (a "
              "utility grab-bag - expected) or is a candidate to look at.")
lines.append("")
lines.append("| Module | Symbols (with a community) | Distinct communities | Top communities (id: count) |")
lines.append("|---|---|---|---|")
for g in sorted(group_communities, key=lambda k: -len(group_communities[k])):
    counter = group_communities[g]
    total = sum(counter.values())
    top = ", ".join(f"{cid}: {cnt}" for cid, cnt in counter.most_common(3))
    lines.append(f"| `src/{g}` | {total} | {len(counter)} | {top} |")
lines.append("")

Path("docs/architecture/module-coupling.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
print("docs/architecture/module-coupling.md written")
print(f"  cross-directory edges: {len(group_edges)}")
print(f"  modules analyzed: {len(group_communities)}")
PYEOF
