#!/usr/bin/env bash
# Phase 4: cross-checks docs/ARCHITECTURE.md's hand-written "Core Components"
# section against docs/graph/GRAPH_REPORT.md's current god nodes, so a
# rename/removal in code or a new load-bearing abstraction that never made it
# into the docs doesn't go unnoticed.
#
# Advisory only - writes docs/architecture/DRIFT.md.
#
# Usage: scripts/check-architecture-drift.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"
mkdir -p docs/architecture

if [ ! -f docs/graph/GRAPH_REPORT.md ] || [ ! -f docs/graph/graph.json ]; then
  echo "[drift] docs/graph/{GRAPH_REPORT.md,graph.json} not found - run scripts/update-knowledge-graph.sh first" >&2
  exit 1
fi

GRAPHIFY_PYTHON="$(cat docs/graph/.graphify_python 2>/dev/null || command -v python3)"

"$GRAPHIFY_PYTHON" <<'PYEOF'
import json
import re
from pathlib import Path

arch_text = Path("docs/ARCHITECTURE.md").read_text(encoding="utf-8")
report_text = Path("docs/graph/GRAPH_REPORT.md").read_text(encoding="utf-8")
graph = json.loads(Path("docs/graph/graph.json").read_text(encoding="utf-8"))

# --- 1. Named "Core Components" from ARCHITECTURE.md §3 ---------------------
components = re.findall(r"^### 3\.\d+ (.+)$", arch_text, flags=re.MULTILINE)

all_labels = {str(n.get("label", "")) for n in graph["nodes"]}
all_labels_lower = {lbl.lower() for lbl in all_labels}


def component_exists_in_graph(name: str) -> bool:
    # "Provider Abstraction" -> look for "Provider"; a documented concept is
    # usually a prose name for one or more concrete graph nodes, not a 1:1
    # label match, so check whether any graph label is contained in (or
    # contains) the component name, case-insensitively.
    name_l = name.lower()
    for lbl in all_labels_lower:
        if lbl and (lbl in name_l or name_l in lbl):
            return True
    return False


# --- 2. God nodes from GRAPH_REPORT.md ---------------------------------------
god_node_lines = re.findall(r"^\d+\. `([^`]+)` - \d+ edges$", report_text, flags=re.MULTILINE)


def mentioned_in_architecture_md(label: str) -> bool:
    # Strip a trailing "()" from function-style labels before searching prose.
    bare = label.rstrip("()")
    return bare != "" and bare in arch_text


lines = []
lines.append("# Architecture Drift Check")
lines.append("")
lines.append("Generated by `scripts/check-architecture-drift.sh`. Advisory only - "
              "cross-checks docs/ARCHITECTURE.md's hand-written prose against "
              "the current knowledge graph. A name match is substring-based, "
              "not semantic, so treat every flag as a lead, not a verdict.")
lines.append("")

lines.append("## Core Components (ARCHITECTURE.md §3) still present in the graph")
lines.append("")
lines.append("| Component (ARCHITECTURE.md §3) | Found in current graph? |")
lines.append("|---|---|")
missing_components = []
for c in components:
    found = component_exists_in_graph(c)
    if not found:
        missing_components.append(c)
    lines.append(f"| {c} | {'yes' if found else 'no - possibly renamed or removed'} |")
lines.append("")
if missing_components:
    lines.append(f"**{len(missing_components)} component(s) documented in ARCHITECTURE.md "
                 "§3 have no matching node in the current graph** - check whether "
                 "they were renamed, removed, or the graph is stale "
                 "(`scripts/update-knowledge-graph.sh`).")
else:
    lines.append("All documented core components have a matching node in the current graph.")
lines.append("")

lines.append("## Top god nodes (GRAPH_REPORT.md) mentioned in ARCHITECTURE.md")
lines.append("")
lines.append("| God node | Mentioned in ARCHITECTURE.md? |")
lines.append("|---|---|")
undocumented = []
for label in god_node_lines:
    found = mentioned_in_architecture_md(label)
    if not found:
        undocumented.append(label)
    lines.append(f"| `{label}` | {'yes' if found else 'no'} |")
lines.append("")
if undocumented:
    lines.append(f"**{len(undocumented)} of the top {len(god_node_lines)} god nodes are never "
                 "named in ARCHITECTURE.md** - each is either covered under a "
                 "different name/section, or a candidate to add to §3.")
else:
    lines.append("Every top god node is mentioned somewhere in ARCHITECTURE.md.")
lines.append("")

Path("docs/architecture/DRIFT.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
print("docs/architecture/DRIFT.md written")
print(f"  components checked: {len(components)}, missing from graph: {len(missing_components)}")
print(f"  god nodes checked: {len(god_node_lines)}, undocumented: {len(undocumented)}")
PYEOF
