#!/usr/bin/env bash
# Phase 2 validation: unused dependencies + import cycles/orphan modules.
# Advisory only - never fails the build. Writes docs/architecture/VALIDATION.md.
#
# Usage: scripts/validate-architecture.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"
mkdir -p docs/architecture

if ! command -v cargo-machete >/dev/null 2>&1; then
  echo "[validate] cargo-machete not found - install with: cargo install cargo-machete" >&2
  exit 1
fi

if [ ! -f docs/graph/graph.json ]; then
  echo "[validate] docs/graph/graph.json not found - run scripts/update-knowledge-graph.sh first" >&2
  exit 1
fi

GRAPHIFY_PYTHON="$(cat docs/graph/.graphify_python 2>/dev/null || command -v python3)"

MACHETE_OUT="$(cargo machete 2>&1 || true)"

"$GRAPHIFY_PYTHON" - "$MACHETE_OUT" <<'PYEOF'
import json
import re
import subprocess
import sys
from pathlib import Path

import networkx as nx

machete_out = sys.argv[1]
repo_root = Path(".")

lines = []
lines.append("# Architecture Validation")
lines.append("")
lines.append("Generated by `scripts/validate-architecture.sh`. Advisory only - "
              "nothing here fails a build; every finding needs a human look "
              "before acting on it (see caveats in each section).")
lines.append("")

# --- Section 1: unused dependencies (cargo machete) -------------------------
lines.append("## Unused Dependencies (cargo-machete)")
lines.append("")

flagged = []
in_list = False
for raw in machete_out.splitlines():
    if "found the following unused dependencies" in raw:
        in_list = True
        continue
    if in_list:
        s = raw.strip()
        if not s or s.endswith("Cargo.toml:"):
            continue
        if s.startswith("If you believe") or not re.match(r"^[A-Za-z0-9_-]+$", s):
            break
        flagged.append(s)

if not flagged:
    lines.append("cargo-machete found no unused dependencies.")
else:
    lines.append("cargo-machete flags these as unused. It does static text "
                  "matching only, so it cannot see macro-injected imports or "
                  "code gated behind a non-default feature - each is "
                  "re-checked here with a whole-repo grep before you trust "
                  "the flag:")
    lines.append("")
    lines.append("| Dependency | grep hit in src/tests/benches? | Verdict |")
    lines.append("|---|---|---|")
    for dep in flagged:
        ident = dep.replace("-", "_")
        found = False
        for d in ("src", "tests", "benches"):
            p = repo_root / d
            if not p.is_dir():
                continue
            try:
                res = subprocess.run(
                    ["grep", "-rlq", "-E", rf"\b{re.escape(ident)}\b", str(p)],
                    capture_output=True,
                )
                if res.returncode == 0:
                    found = True
                    break
            except OSError:
                pass
        verdict = (
            "possibly used (behind a feature/macro) - verify manually"
            if found
            else "no reference found anywhere - candidate for removal"
        )
        lines.append(f"| `{dep}` | {'yes' if found else 'no'} | {verdict} |")
lines.append("")

# --- Section 2: import cycles + orphan modules (docs/graph/graph.json) ------
lines.append("## Import Cycles & Orphan Modules (docs/graph/graph.json)")
lines.append("")
lines.append("Built from `imports_from` edges between whole-file nodes only "
              "(not symbol-level calls/references, which cycle constantly in "
              "normal Rust code and aren't a useful signal here).")
lines.append("")

graph = json.loads(Path("docs/graph/graph.json").read_text(encoding="utf-8"))
nodes = {n["id"]: n for n in graph["nodes"]}


def is_file_node(n: dict) -> bool:
    return n.get("source_location") == "L1" and str(n.get("label", "")).endswith(".rs")


file_nodes = {nid: n for nid, n in nodes.items() if is_file_node(n)}
all_source_files = sorted({n["source_file"] for n in file_nodes.values()})

# imports_from mostly targets a specific symbol, not a file's own L1 node
# (e.g. `use crate::services::file::FileService` targets the FileService
# node, not a node representing file.rs itself) - so build the file-level
# graph from each edge endpoint's *source_file*, not the endpoint id itself.
dg = nx.DiGraph()
dg.add_nodes_from(all_source_files)
for e in graph["links"]:
    if e.get("relation") != "imports_from":
        continue
    s_node, t_node = nodes.get(e.get("source")), nodes.get(e.get("target"))
    if not s_node or not t_node:
        continue
    s_file, t_file = s_node.get("source_file"), t_node.get("source_file")
    if s_file and t_file and s_file != t_file:
        dg.add_edge(s_file, t_file)

# A parent `mod.rs` referencing a submodule it declares (and vice versa,
# e.g. the submodule using a type re-exported from `super`) is structural to
# Rust's module system, not a design smell - exclude same-directory
# mod.rs<->sibling edges from cycle detection (they still count for orphan
# in-degree above, since that relationship is a legitimate "use").
def _is_modrs_sibling_edge(a: str, b: str) -> bool:
    a_dir, a_name = a.rsplit("/", 1) if "/" in a else ("", a)
    b_dir, b_name = b.rsplit("/", 1) if "/" in b else ("", b)
    return a_dir == b_dir and (a_name == "mod.rs" or b_name == "mod.rs")


dg_cycles = nx.DiGraph()
dg_cycles.add_nodes_from(all_source_files)
for u, v in dg.edges():
    if not _is_modrs_sibling_edge(u, v):
        dg_cycles.add_edge(u, v)

cycles = list(nx.simple_cycles(dg_cycles))
lines.append(f"### Cycles ({len(cycles)} found)")
lines.append("")
lines.append("Excludes same-directory `mod.rs` <-> submodule edges, which are "
              "structural to Rust's module system, not a design smell.")
lines.append("")
if not cycles:
    lines.append("No import cycles detected among source files.")
else:
    for cyc in cycles[:25]:
        path = " -> ".join(cyc) + " -> " + cyc[0]
        lines.append(f"- {path}")
    if len(cycles) > 25:
        lines.append(f"- ... and {len(cycles) - 25} more")
lines.append("")

ENTRY_POINTS = {"main.rs", "lib.rs", "mod.rs"}


def is_test_or_bench(source_file: str) -> bool:
    return source_file.startswith("tests/") or source_file.startswith("benches/")


def is_own_bin_target(source_file: str) -> bool:
    # Each file directly under src/bin/ is its own `fn main()` binary target,
    # never imported by other files - same category as main.rs.
    return source_file.startswith("src/bin/")


orphan_candidates = []
for sf in all_source_files:
    fname = sf.rsplit("/", 1)[-1]
    if fname in ENTRY_POINTS or is_test_or_bench(sf) or is_own_bin_target(sf):
        continue
    if dg.in_degree(sf) == 0:
        orphan_candidates.append(sf)

lines.append(f"### Orphan Modules ({len(orphan_candidates)} graph-only candidates)")
lines.append("")
lines.append("`imports_from` extraction misses some import styles - notably "
              "`use super::x::y` relative imports, confirmed by spot-check "
              "during Phase 2 (see e.g. `src/tui/highlight.rs`, imported by "
              "`src/tui/markdown.rs` via `use super::highlight::...` but not "
              "captured as an edge). Every graph-only candidate is therefore "
              "re-checked with a whole-repo grep for its module name before "
              "being called a real orphan:")
lines.append("")
if not orphan_candidates:
    lines.append("None found.")
else:
    lines.append("| File | grep hit elsewhere? | Verdict |")
    lines.append("|---|---|---|")
    real_orphans = 0
    for sf in sorted(orphan_candidates):
        stem = sf.rsplit("/", 1)[-1].removesuffix(".rs")
        found = False
        # Two legitimate "this file is used" patterns the graph can miss:
        # `stem::` (path reference) and `mod stem;` (module declaration,
        # e.g. a test file split out and pulled in via `mod foo_tests;`).
        pattern = rf"\b{re.escape(stem)}::|\bmod\s+{re.escape(stem)}\b"
        try:
            res = subprocess.run(
                ["grep", "-rl", "-E", pattern, "src"],
                capture_output=True, text=True,
            )
            hits = [
                line for line in res.stdout.splitlines()
                if line.replace("\\", "/") != sf
            ]
            found = bool(hits)
        except OSError:
            pass
        if found:
            verdict = "referenced elsewhere - graph missed the edge, not orphaned"
        else:
            verdict = "no reference found anywhere - candidate for removal"
            real_orphans += 1
        lines.append(f"| `{sf}` | {'yes' if found else 'no'} | {verdict} |")
    lines.append("")
    lines.append(f"**{real_orphans} of {len(orphan_candidates)}** candidates "
                  "found no reference either in the graph or via grep.")
lines.append("")

Path("docs/architecture/VALIDATION.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
print("docs/architecture/VALIDATION.md written")
print(f"  unused deps flagged: {len(flagged)}")
print(f"  import cycles: {len(cycles)}")
print(f"  orphan module candidates: {len(orphan_candidates)}")
PYEOF
